### ISSUE TITLE
Add a readme file

### ISSUE THREAD

**Issue by pattyf** [dlab-geo/RGeo_workshop#3]
Add a readme file with:

- links to the html slides/notebook in the docs directory so folks can click and view in the browser.
- Details on prerequisite knowledge, packages, getting started etc - the stuff in the setup slide.

**Comment by pattyf** [comment]
You have the readme file but it needs to be updated as described above, current links point to sp materials.

**Comment by drewhart** [comment]
Taken care of (but I'll be continuing to update the code in here as I figure out how to get this all running, and to reflect the new repo names and URLs once we have them).
